name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons:main

      - name: Build release
        run: flutter build appbundle --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab
